// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CircleCharts: typeof import('./src/components/circleCharts/index.vue')['default']
    CityMap: typeof import('./src/components/cityMap/index.vue')['default']
    CountRate: typeof import('./src/components/countRate/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    'Index copy': typeof import('./src/components/listCard/index copy.vue')['default']
    'Index copy 2': typeof import('./src/components/listCard/index copy 2.vue')['default']
    LineCharts: typeof import('./src/components/lineCharts/index.vue')['default']
    ListCard: typeof import('./src/components/listCard/index.vue')['default']
    Loading: typeof import('./src/components/MyLoading/loading.vue')['default']
    MyEarth: typeof import('./src/components/MyEarth/index.vue')['default']
    MyEcharts: typeof import('./src/components/MyEcharts/index.vue')['default']
    MyStart: typeof import('./src/components/MyStart/index.vue')['default']
    MySwitch: typeof import('./src/components/MySwitch/index.vue')['default']
    MyTime: typeof import('./src/components/MyTime/index.vue')['default']
    PublicSelect: typeof import('./src/components/publicSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTable: typeof import('./src/components/scrollTable/index.vue')['default']
  }
}

export {}
