// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Loading: typeof import('./src/components/MyLoading/loading.vue')['default']
    MyEarth: typeof import('./src/components/MyEarth/index.vue')['default']
    MyEcharts: typeof import('./src/components/MyEcharts/index.vue')['default']
    MyStart: typeof import('./src/components/MyStart/index.vue')['default']
    MySwitch: typeof import('./src/components/MySwitch/index.vue')['default']
    MyTime: typeof import('./src/components/MyTime/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTable: typeof import('./src/components/scrollTable/index.vue')['default']
  }
}

export {}
