export default {
  公证办理: {
    ajbjl: "案件办件量",
    gzjgsl: "公证机构数量",
    gzyqksl: "公证员数量",
  },
  行政复议: {
    slz: "审理中",
    ss: "胜诉",
    yyzs: "复议总数",
    ysj: "已审结",
    bs: "败诉",
    jcl: "纠错率",
    tjl: "调解率",
    bsl: "败诉率",
    yszs: "应诉总数",
    yzzytczs: "行政争议调处总数",
  },
  行政规范性文件: {
    xxyx: "现行有效",
  },
  人民调解案件总数: {
    rmtjajHtjf: "合同纠纷",
    rmtjajShpcjf: "损害赔偿纠纷",
    rmtjajLljf: "邻里纠纷",
    rmtjajAjzs: "调解案件总数",
    rmtjajWygljf: "物业管理纠纷",
    rmtjajZdcjjf: "征地拆迁纠纷",
    rmtjajHyjf: "婚姻家庭纠纷",
    rmtjajLdzyjf: "劳动争议纠纷",
    rmtjajZjdjf: "房屋宅基地纠纷",
    rmtjajTjcg: "调解成功",
    rmtjajDljtsgjf: "道路交通事故纠纷",
    rmtjajQtjf: "其他纠纷",
  },
  基础工作: {
    sfs: "司法所",
    rmtjy: "人民调解员",
    sfsgzry: "司法所工作人员",
    flfws: "基层法律服务所",
    flfwgzz: "基层法律服务工作者",
    rmtjzz: "人民调解组织",
  },
  社区矫正: {
    hx: "缓刑",
    zcrs: "在册人数",
    gz: "管制",
    js: "假释",
    jwzx: "暂予监外执行",
  },
  仲裁服务: {
    hj: "合计",
    qt: "其他",
    jrlaj: "金融类案件",
    fcjf: "房产纠纷",
    jsgcaj: "建设工程案件",
    mmjf: "买卖纠纷",
  },
  法律援助案件类型分析: {
    ajlxMs: "民事",
    ajlxXz: "行政",
    ajlxXs: "刑事",
  },
  司法鉴定: {
    jgSl: "机构数量",
    ajBjs: "办件量",
    ryRysl: "人员数量",
  },
  行政执法监督: {
    ycyzj: "已持有行政执法员证件",
    yzzytczs: "正在申请办证",
  },
  行政立法: {
    xzd: "本年度制定(修改)",
    fz: "本年度废止",
    xxyy: "现行有效",
  },
  律师业务: {
    lssl: "律所数量",
    lsqkLssl: "律师数量",
    lsbjajsl: "律所办理案件数量",
  },
  公共法律服务平台数据: {
    fwfsSt: "实体",
    fwfsWl: "网络",
    fwfsDh: "热线",
    zxzs: "咨询总数",
    ajzs: "案件总数",
  },
  法律援助对象: {
    yzdxLnr: "老年人/儿童",
    yzdxNmg: "农民/农民工",
    yzdxFn: "妇女",
  },
  法律援助案件类型: {
    ajlxMs: "民事",
    ajlxXz: "行政",
    ajlxXs: "刑事",
  },
  本月服务: {
    fwnrLs: "律师",
    fwnrGz: "公证",
    fwnrFy: "法援",
    fwfsSt: "实体",
    fwfsWl: "网络",
    fwfsDh: "热线",
  },
  服务数量类型分析: {
    fwnrLs: "律师",
    fwnrGz: "公证",
    fwnrFy: "法援",
    fwfsSt: "实体",
    fwfsWl: "网络",
    fwfsDh: "热线",
  },
  服务内容: {
    fwnrLs: "律师",
    fwnrGz: "公证",
    fwnrFy: "法援",
  },
  服务方式: {
    fwfsSt: "实体",
    fwfsWl: "网络",
    fwfsDh: "热线",
  },
  qslist: {
    xz: "行政",
    sx: "刑事",
    ms: "民事",
  },
};
